# monitor info (single laptop)
monitor=,1920x1080@60,auto,1.25

# programs
source = ~/.config/hypr/programs.conf

# autostart
source = ~/.config/hypr/autostart.conf

# swaync rules (temp)
layerrule = blur on, match:namespace swaync-control-center
layerrule = animation slide right, match:namespace swaync-control-center
layerrule = ignore_alpha 0.0, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.0, match:namespace swaync-control-center

# binds
source = ~/.config/hypr/binds.conf

# window rules
source = ~/.config/hypr/windowrules.conf

# cursor settings
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# customization
source = ~/.config/hypr/look.conf

# input
source = ~/.config/hypr/input.conf

# windows & workspaces
source = ~/.config/hypr/window-workspaces.conf
